[project]
name = "child-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.131.0",
    "loguru>=0.7.3",
    "pydantic>=2.12.5",
    "uvicorn>=0.41.0",
]
